import globals from "globals";

export default [
    {
        files: ["**/*.js"],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "script",
            globals: {
                ...globals.browser,
                Utils: "readonly",
                toast: "readonly",
                Chart: "readonly",
                Papa: "readonly",
                PromptDialog: "readonly",
                ModalManager: "readonly",
                console: "readonly",
                savePlot: "readonly",
                testData: "readonly",
                generateAllPlots: "readonly",
                openCustomPlot: "readonly",
                addConstantLine: "readonly",
                removeConstantLine: "readonly",
                generateCustomPlot: "readonly",
                openVenturiModal: "readonly",
                setVenturiDensity: "readonly",
                calculateVenturiMdot: "readonly",
                bootstrap: "readonly",
                cdaLoadCSV: "readonly",
                cdaUpdateColumn: "readonly",
                openTimeSelectionPlot: "readonly",
                resetTimeSelection: "readonly",
                confirmTimeSelection: "readonly",
                useAvgPressure: "readonly",
                setAmbientPressure: "readonly",
                selectPLowFromCSV: "readonly",
                applyPLowColumn: "readonly",
                calculateCdA: "readonly",
                copyCalculatedCdA: "readonly",
                copyCalculatedMdot: "readonly",
                setDensityPreset: "readonly",
                calculateSetPressure: "readonly",
                loadCSV: "readonly",
                confirmColumnSelection: "readonly",
                updateSliderDisplay: "readonly",
                updateExtraDataSlider: "readonly",
                toggleCustomSplice: "readonly",
                applySplice: "readonly",
                showInstructions: "readonly",
                closePlotModal: "readonly",
                updateSmoothing: "readonly",
                plotThrust: "readonly",
                plotChamberPressure: "readonly",
                plotOFRatio: "readonly",
                plotFuelWeight: "readonly",
                plotOxidizerWeight: "readonly",
                plotExhaustVelocity: "readonly",
                plotISP: "readonly",
                plotCStar: "readonly",
            },
        },
        rules: {
            "no-unused-vars": "off",
            "no-undef": "warn",
            "semi": ["error", "always"],
        }
    }
];
